clusterName: loopback

agentDeploymentName: cluster-proxy-proxy-agent

includeNamespaceCreation: false

proxyAgentImage: quay.io/open-cluster-management/cluster-proxy:latest
proxyAgentImagePullSecrets: []

# Number of replicas
replicas: 1

spokeAddonNamespace: "open-cluster-management-cluster-proxy"
additionalProxyAgentArgs: []

agentDeploymentAnnotations: {}

addonAgentArgs: []

serviceEntryPoint: ""
serviceEntryPointPort: 8091

base64EncodedCAData: Zm9vCg==

serviceDomain: ""

tolerations: []

nodeSelector: {}
proxyConfig:
  HTTP_PROXY: null
  HTTPS_PROXY: null
  NO_PROXY: null
